# Generated by Django 3.2.6 on 2021-08-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('title', models.CharField(max_length=500, verbose_name='title of subject')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='subject id')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='question id')),
                ('question', models.TextField(verbose_name='questions')),
                ('author', models.CharField(max_length=500, verbose_name='author of question')),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject', to='backend.subject', verbose_name='Subject Id')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer', models.TextField(verbose_name='answer')),
                ('author', models.CharField(max_length=500, verbose_name='author of answer ')),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Answer  id')),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='backend.question', verbose_name='Question Id')),
            ],
        ),
    ]
